# Generated by Django 5.0.3 on 2024-03-23 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="iamge",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="is_sold",
            new_name="vendido",
        ),
    ]
