# Generated by Django 5.0.3 on 2024-03-25 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_rename_iamge_item_image_rename_is_sold_item_vendido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="description",
            new_name="descripcion",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="image",
            new_name="imagen",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="name",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="price",
            new_name="precio",
        ),
    ]
